FROM ubuntu:18.04


RUN apt-get update \
    && apt-get install -y python3 python3-pip\
    && apt-get install -y software-properties-common \
    && apt-get install -y libsm6 libxrender1 libxext-dev \
    && pip3 install tensorboard \
            future \
            lmdb \
            opencv-python==4.1.1.26 \
            pyyaml \
            matplotlib \
            tqdm \
            pillow==6.2.1 \
    && pip3 install torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html \
    && pip3 uninstall torch \
    && pip3 install https://download.pytorch.org/whl/cu100/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl \
    && add-apt-repository ppa:savoury1/ffmpeg4 \
    && add-apt-repository ppa:savoury1/graphics \
    && add-apt-repository ppa:savoury1/multimedia \
    && apt-get update \
    && apt-get install -y ffmpeg

COPY . /

RUN chmod 777 /run_train.sh
CMD ["/bin/bash", "-c", "/run_train.sh"]

