FROM pytorch/pytorch:1.2-cuda10.0-cudnn7-devel


RUN apt-get update \
    && apt-get install -y python3 python3-pip\
    && apt-get install -y software-properties-common \
    && pip3 install tensorboard \
            future \
            lmdb \
            opencv-python \
            pyyaml \
            matplotlib \
            tqdm \
    && pip3 install torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html \
    && add-apt-repository ppa:savoury1/ffmpeg4 \
    && add-apt-repository ppa:savoury1/graphics \
    && add-apt-repository ppa:savoury1/multimedia \
    && apt-get update \
    && apt-get install -y ffmpeg

COPY . /

RUN chmod 777 /run_train.sh
CMD ["/bin/bash", "-c", "/run_train.sh"]

