FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

RUN  sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN  apt-get clean

RUN apt-get update \
    && apt-get install -y python3 python3-pip\
    && apt-get install -y software-properties-common \
    && apt-get install -y libsm6 libxrender1 libxext-dev \
    && pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple tensorboard \
            future \
            lmdb \
            opencv-python==4.1.1.26 \
            pyyaml \
            matplotlib \
            tqdm \
            pillow==6.2.1

RUN apt install -y wget \
    && apt install -y yasm \
    && apt install -y libass \
    && wget https://ffmpeg.org/releases/ffmpeg-4.2.2.tar.bz2 \
    && tar -jxvf ffmpeg-4.2.2.tar.bz2 \
    && cd ffmpeg-4.2.2 \
    && ./configure  --enable-libass \
    && make \
    && make install

COPY . /

RUN pip3 install ./torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl \
    && pip3 install torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html
RUN chmod 777 /run_test.sh
CMD ["/bin/bash", "-c", "/run_test.sh"]
    

